name: Sync Scripts to GitHub Pages

on:
  push:
    branches: [ main ]

permissions:
  contents: write

jobs:
  copy-scripts-to-docs:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Copy all .js files from src/ to docs/
        run: |
          mkdir -p docs
          find src -name "*.js" -exec cp {} docs/ \;

      - name: Commit updated docs/
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add docs/
          git diff --quiet && git diff --staged --quiet || git commit -m "🔄 Update docs with latest scripts"
          git push
